# Generated by Django 3.1.7 on 2022-01-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20220110_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coverphoto',
            field=models.ImageField(default='cover.jpg', upload_to='cover'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profilephoto',
            field=models.ImageField(default='profile.jpg', upload_to='profile'),
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
