# Generated by Django 3.1.7 on 2021-11-04 01:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0011_auto_20211103_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets',
            name='retweet',
        ),
        migrations.AddField(
            model_name='tweets',
            name='retweet',
            field=models.ManyToManyField(blank=True, related_name='retweet', to=settings.AUTH_USER_MODEL),
        ),
    ]
