# Generated by Django 3.1.7 on 2021-12-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
